packages:
  - packages/*

linkWorkspacePackages: true
preferWorkspacePackages: true

overrides:
  '@types/babel__traverse': 7.28.0
  '@types/lodash': 4.17.24
  '@use-gesture/react': 10.3.1
  dayjs: 1.11.21
  eslint-config-za: 2.4.0-alpha.3
  lerna>jest-diff: 30.3.0
  sass: 1.101.0
  stylelint-config-recommended-scss: 4.2.0
  stylelint-scss: 3.19.0
  webpack: 5.108.4
