// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { history, useOutlet } from 'dumi';
import { useEffect, useRef, useState } from 'react';

import './nprogress.css';
import nprogress from '/Users/dominicleo/za/zarm/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';

import { locales } from '../locales/config';
import { components, demos } from '../meta';
import { SiteContext } from '/Users/dominicleo/za/zarm/node_modules/.pnpm/dumi@2.2.1_7700272a42f35b82f4df09ea36057196/node_modules/dumi/dist/client/theme-api/context.js';

const entryExports = {};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // start nprogress
        nprogress.start();

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider
      value={{
        pkg: { name: 'site-next', license: 'MIT' },
        historyType: 'browser',
        entryExports,
        demos,
        components,
        locales,
        loading,
        setLoading,
        hostname: undefined,
        themeConfig: {
          footer:
            'Copyright © 2023 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
          prefersColor: { default: 'auto', switch: true },
          nprogress: true,
          name: 'Zarm Design',
          logo: 'https://zarm.design/images/logo.1a6cfc30.svg',
          version: '3.0.14',
          autoAlias: {},
        },
        _2_level_nav_available: true,
      }}
    >
      {outlet}
    </SiteContext.Provider>
  );
}
