// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    GlobalLayout: {
      id: 'GlobalLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true,
    },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'GlobalLayout', isLayout: true },
    'index/components/Navigation': {
      path: 'index/components/navigation',
      id: 'index/components/Navigation',
      parentId: 'DocLayout',
    },
    'index/components/Introduce': {
      path: 'index/components/introduce',
      id: 'index/components/Introduce',
      parentId: 'DocLayout',
    },
    'index/components/Banner': {
      path: 'index/components/banner',
      id: 'index/components/Banner',
      parentId: 'DocLayout',
    },
    'index/components/index': {
      path: 'index/components',
      id: 'index/components/index',
      parentId: 'DocLayout',
    },
    'index-cn/index': { path: 'index-cn', id: 'index-cn/index', parentId: 'DocLayout' },
    'index/index': { path: '', id: 'index/index', parentId: 'DocLayout' },
    'docs/guide/customize-theme-en-US': {
      path: 'guide/customize-theme-en--us',
      id: 'docs/guide/customize-theme-en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/customize-theme-zh-CN': {
      path: 'guide/customize-theme-zh--cn',
      id: 'docs/guide/customize-theme-zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/contributing.en-US': {
      path: 'guide/contributing',
      id: 'docs/guide/contributing.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/contributing.zh-CN': {
      path: 'guide/contributing-cn',
      id: 'docs/guide/contributing.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/installation.en-US': {
      path: 'guide/installation',
      id: 'docs/guide/installation.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/installation.zh-CN': {
      path: 'guide/installation-cn',
      id: 'docs/guide/installation.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/migration-v3.en-US': {
      path: 'guide/migration-v3',
      id: 'docs/guide/migration-v3.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/migration-v3.zh-CN': {
      path: 'guide/migration-v3-cn',
      id: 'docs/guide/migration-v3.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/about-zarm.zh-CN': {
      path: 'guide/about-zarm-cn',
      id: 'docs/guide/about-zarm.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/changelog.en-US': {
      path: 'guide/changelog',
      id: 'docs/guide/changelog.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/changelog.zh-CN': {
      path: 'guide/changelog-cn',
      id: 'docs/guide/changelog.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/polyfill.en-US': {
      path: 'guide/polyfill',
      id: 'docs/guide/polyfill.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/polyfill.zh-CN': {
      path: 'guide/polyfill-cn',
      id: 'docs/guide/polyfill.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/guide/about.en-US': {
      path: 'guide/about',
      id: 'docs/guide/about.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/i18n.en-US': {
      path: 'guide/i18n',
      id: 'docs/guide/i18n.en-US',
      parentId: 'DocLayout',
    },
    'docs/guide/i18n.zh-CN': {
      path: 'guide/i18n-cn',
      id: 'docs/guide/i18n.zh-CN',
      parentId: 'DocLayout',
    },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'components/button/index.en-US': {
      id: 'components/button/index.en-US',
      path: 'components/button',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'components/button/index.zh-CN': {
      id: 'components/button/index.zh-CN',
      path: 'components/button-cn',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'GlobalLayout' },
    gallery: { id: 'gallery', path: 'gallery', parentId: 'GlobalLayout' },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__404" */ '@/dumi__pages/404'),
      ),
      GlobalLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__GlobalLayout" */ '@/dumi__theme__layouts/GlobalLayout'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__ContextWrapper" */ '@/dumi__theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DocLayout" */ '@/dumi__theme__layouts/DocLayout'
          ),
      ),
      'index/components/Navigation': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__components__Navigation" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index/components/Navigation.tsx'
          ),
      ),
      'index/components/Introduce': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__components__Introduce" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index/components/Introduce.tsx'
          ),
      ),
      'index/components/Banner': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__components__Banner" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index/components/Banner.tsx'
          ),
      ),
      'index/components/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__components__index" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index/components/index.ts'
          ),
      ),
      'index-cn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index-cn__index" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index-cn/index.tsx'
          ),
      ),
      'index/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__index" */ '/Users/dominicleo/za/zarm/site/.dumi/pages/index/index.tsx'
          ),
      ),
      'docs/guide/customize-theme-en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__customize-theme-en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/customize-theme-en-US.md'
          ),
      ),
      'docs/guide/customize-theme-zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__customize-theme-zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/customize-theme-zh-CN.md'
          ),
      ),
      'docs/guide/contributing.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__contributing.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/contributing.en-US.md'
          ),
      ),
      'docs/guide/contributing.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__contributing.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/contributing.zh-CN.md'
          ),
      ),
      'docs/guide/installation.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__installation.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/installation.en-US.md'
          ),
      ),
      'docs/guide/installation.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__installation.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/installation.zh-CN.md'
          ),
      ),
      'docs/guide/migration-v3.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__migration-v3.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/migration-v3.en-US.md'
          ),
      ),
      'docs/guide/migration-v3.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__migration-v3.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/migration-v3.zh-CN.md'
          ),
      ),
      'docs/guide/about-zarm.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__about-zarm.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/about-zarm.zh-CN.md'
          ),
      ),
      'docs/guide/changelog.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__changelog.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/changelog.en-US.md'
          ),
      ),
      'docs/guide/changelog.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__changelog.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/changelog.zh-CN.md'
          ),
      ),
      'docs/guide/polyfill.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__polyfill.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/polyfill.en-US.md'
          ),
      ),
      'docs/guide/polyfill.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__polyfill.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/polyfill.zh-CN.md'
          ),
      ),
      'docs/guide/about.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__about.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/about.en-US.md'
          ),
      ),
      'docs/guide/i18n.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__i18n.en-US.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/i18n.en-US.md'
          ),
      ),
      'docs/guide/i18n.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__i18n.zh-CN.md" */ '/Users/dominicleo/za/zarm/site/docs/guide/i18n.zh-CN.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/dominicleo/za/zarm/site/docs/index.md'
          ),
      ),
      'components/button/index.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__zarm__src__button__index.en-US.md" */ '/Users/dominicleo/za/zarm/packages/zarm/src/button/index.en-US.md'
          ),
      ),
      'components/button/index.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__zarm__src__button__index.zh-CN.md" */ '/Users/dominicleo/za/zarm/packages/zarm/src/button/index.zh-CN.md'
          ),
      ),
      'demo-render': React.lazy(
        () => import(/* webpackChunkName: "dumi__pages__Demo" */ '@/dumi__pages/Demo'),
      ),
      gallery: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__gallery__index" */ '/Users/dominicleo/za/zarm/site/.dumi/gallery/index.tsx'
          ),
      ),
    },
  };
}
