export const DEFAULT_THEME_CONFIG = {
  name: 'Zarm',
  logo: 'https://zarm.design/images/logo.1a6cfc30.svg',
  categoryOrder: {
    Zarm: 0,
    Components: 100,
    组件: 100,
  },
  typeOrder: {
    Overview: -1,
    General: 0,
    Layout: 1,
    Navigation: 2,
    'Data Entry': 3,
    'Data Display': 4,
    Feedback: 5,
    Other: 6,
    Deprecated: 7,

    组件总览: -1,
    通用: 0,
    布局: 1,
    导航: 2,
    数据录入: 3,
    数据展示: 4,
    反馈: 5,
    其他: 6,
    废弃: 7,

    // Design
    原则: 1,
    Principles: 1,
    全局规则: 2,
    重型组件: 8,
    ProComponents: 8,
    'Global Rules': 2,
    模板文档: 3,
    'Template Document': 3,
  },
};
