// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from '/Users/dominicleo/za/zarm/packages/zarm/src/button/index.en-US.$tab-mini.md';
import * as tab1 from '/Users/dominicleo/za/zarm/packages/zarm/src/button/index.zh-CN.$tab-mini.md';

export const tabs = {
  '../packages/zarm/src/button/index.en-US.$tab-mini': {
    key: 'mini',
    title: '',
    titleIntlId: '',
    components: tab0,
  },
  '../packages/zarm/src/button/index.zh-CN.$tab-mini': {
    key: 'mini',
    title: '',
    titleIntlId: '',
    components: tab1,
  },
};
