// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/dominicleo/za/zarm/node_modules/.pnpm/dumi@2.2.1_7700272a42f35b82f4df09ea36057196/node_modules/dumi/theme-default/builtins/Table/index.js';
