name: Deploy website
on:
  workflow_dispatch:
  release:
    types: [published]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.34.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: pnpm

      - name: install
        run: |
          pnpm --version
          pnpm install --frozen-lockfile

      - name: build
        run: pnpm deploy:build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./packages/site/assets
          allow_empty_commit: false
