name: Sync mirror to Gitee
on: 
  delete:
  push:
    branches:
      - master
      - feature
      - gh-pages

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: mirror to gitee
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:zarm/zarm.git
          ssh_private_key:
            ${{ secrets.GITEE_SSH_KEY }}
