name: Test
on: [push, pull_request]

jobs:
  test-cli:
    name: Test CLI on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm --filter @zarm-design/cli test --coverage

      - name: Coverage
        if: matrix.node-version == 20
        run: bash <(curl -s https://codecov.io/bash)

  test-react-17:
    name: Test and build with React 17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm --filter zarm coverage

      - name: Build
        run: pnpm --filter zarm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Check dist
        run: pnpm --filter zarm exec node ./tests/dekko/dist.test.js

      - name: Check bundle size
        run: pnpm --filter zarm exec bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}

      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)

  test-react-16:
    name: Test and build with React 16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install React 16
        run: pnpm --filter zarm install-react-16 --lockfile=false

      - name: Test
        run: pnpm --filter zarm test

      - name: Build
        run: pnpm --filter zarm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Check dist
        run: pnpm --filter zarm exec node ./tests/dekko/dist.test.js

      - name: Check bundle size
        run: pnpm --filter zarm exec bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
